### ISSUE TITLE
Feature request: make Wine branch configurable

### ISSUE THREAD

**Issue by harenber** [JakobLichterfeld/ansible-role-winehq#2]
I'd like to ask if you would consider making the wine branch (stable, staging, devel) configurable. 

Backgrund: at least for Ubuntu 24.04 LTS "noble", there is (currently?) no stable branch availble (see [here](https://dl.winehq.org/wine-builds/ubuntu/dists/noble/main/binary-amd64/)), so your rule will fail: 

```
TASK [jakoblichterfeld.winehq : Install WineHQ] ********************************
fatal: [plus]: FAILED! => {"changed": false, "msg": "No package matching 'winehq-stable' is available"}
```

I waited for a couple of days, but the Wine team doesn't seem to have one in the pipeline.

Thanks for your consideration :).

**Comment by JakobLichterfeld** [comment]
Thanks for reporting.

"There are no stable packages yet for 24.04 because 24.04 was not released when Wine 9.0 came out. There will be stable packages whenever 9.0.1 comes out." (See https://forum.winehq.org/viewtopic.php?t=39006)

The automated tests didn't cover this, as this role is only released for Ubuntu 22.04 and automatically tested for 22.04.

Lets see if we can fix it.
